#!/usr/bin/env bash

set -eo pipefail

source _test/config.sh

cd "${TEST_ROOT_DIR}"

source _test/lib.sh
source _test/gke.sh

if [ "${TRAVIS}" == true ]; then
  if [ "${TRAVIS_PULL_REQUEST}" != false ]; then
    log-lifecycle "This is a pull request build. Skipping chart tests."
    exit 0
  fi

  # decrypt gcloud credentials if on Travis and building the master branch
  openssl aes-256-cbc -K $encrypted_e967971bb2cd_key \
          -iv $encrypted_e967971bb2cd_iv \
          -in _test/secrets/gcloud-credentials.json.enc \
          -out _test/secrets/gcloud-credentials.json -d
fi

trap gke-destroy EXIT ERR

setup-gke

install-helm

run-test-plan
